ODM-8670: Set host as mandatory
genestack/python-client pull request #347
Opened 2022-11-09 22:14 UTC by nzorkic-genestack

2022-11-10 14:02 UTC, m-smazhevsky requested changes

2022-11-10 14:10 UTC, nzorkic-genestack commented on genestack_client/scripts/genestack_user_setup.py
> +                           help='Genestack host,',
Because Default host has been removed. Do you have some suggestion?

2022-11-10 14:13 UTC, m-smazhevsky commented on genestack_client/scripts/genestack_user_setup.py
> +                           help='Genestack host,',
currently there is a comma in the end, probably smth simple like
'Genestack host address'

2022-11-10 22:37 UTC, m-smazhevsky approved these changes
Let's wait for Nikolay

2022-11-13 09:04 UTC, klas-genestack approved these changes

2022-11-14 08:32 UTC, merged