test 3.11 python
genestack/python-client pull request #372
Opened 2023-03-08 20:48 UTC by genestack-okunitsyn

2023-03-09 07:34 UTC, klas-genestack requested changes
Update `classifiers` in `setup.py` as well, then =)

2023-03-09 07:35 UTC, klas-genestack commented on genestack_client/share_util.py
> +    collectionsAbc = collections
Where is this import used?

2023-03-09 17:43 UTC, genestack-okunitsyn commented on genestack_client/share_util.py
> +    collectionsAbc = collections
Autotests and publicDataLoader.

2023-03-09 17:48 UTC, genestack-okunitsyn commented
> Update `classifiers` in `setup.py` as well, then =)

done.

2023-03-10 08:54 UTC, tropnikovvl approved these changes

2023-03-10 09:01 UTC, klas-genestack approved these changes

2023-03-10 10:34 UTC, merged