ODM-5452 move gene dictionaries to sdk
genestack/python-client pull request #431
Opened 2024-03-06 13:16 UTC by natalyatodorova

- The` generate_gene_dictionaries.py` is based on `initialise_raw_gene_dictionary.py`from unified for review it's better to refer to original, because I haven't invented the algorythm. Just `get_ensembl_organisms` method has been taken from `gene_dictionary_creation.py`.
- added readme
- upload gene dictionaries in `upload_dictionaries_with_specific_metainfo.py `

2024-03-06 14:19 UTC, genestack-okunitsyn approved these changes, later dismissed

2024-03-07 15:38 UTC, m-smazhevsky requested changes
Nice! Just 2 small comments

2024-03-07 15:38 UTC, m-smazhevsky commented on odm_sdk/scripts/internal/README.md
> +uploaded by the initial image. The source files can be found in the `odm-init` S3 bucket. These scripts serve as a
initial image -> init image + link to repo

2024-03-07 15:38 UTC, m-smazhevsky commented on odm_sdk/scripts/internal/README.md
> +backup solution in case the original data is lost.
```suggestion
backup solution in case the original data is lost. They can be also used to get the most recent version of the dictionaries.
```

2024-03-08 09:09 UTC, natalyatodorova commented on odm_sdk/scripts/internal/README.md
> +backup solution in case the original data is lost.
I decided not apply this suggestion, because we actually are using old ensembl version (published in 2019), which is hardcoded. So `most recent version` might be confusing.

2024-03-08 09:57 UTC, m-smazhevsky approved these changes

2024-03-08 10:00 UTC, merged